### ISSUE TITLE
Some Python errors when running gogrepo.py update

### ISSUE THREAD

**Issue by ghost** [sairuk/gogrepo#4]
Hi, I'm seeing a few errors when running the `gogrepo.py update` command. This seems to happen across multiple runs, but only on a few specific games. Most of my library completes the md5 checks no problem.

The command I'm using is `python gogrepo.py update -os windows -lang en`

I'm running under WSL V2 on Windows 10  with Ubuntu 20.04.4 LTS and Python 3.8.10

```
14:46:30 | ( 67 / 285) fetching game details for fallout_3_game_of_the_year_edition_game...
14:46:38 | successfully found md5 ff6af1e079c63b1a8c073f791c446ea9 for setup_fallout_3_1.7.0.3_(12034).exe
14:46:41 | error
Traceback (most recent call last):
  File "gogrepo.py", line 722, in cmd_update
    filter_downloads(item.downloads, item_json_data['downloads'], lang_list, os_list)
  File "gogrepo.py", line 411, in filter_downloads
    fetch_file_info(d, True)
  File "gogrepo.py", line 368, in fetch_file_info
    shelf_etree = xml.etree.ElementTree.fromstring(gzip.decompress(page.read()))
  File "/usr/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 14263 more expected)
```

```
14:47:14 | ( 70 / 285) fetching game details for fallout_new_vegas_ultimate_edition_game...
14:47:25 | error
Traceback (most recent call last):
  File "gogrepo.py", line 722, in cmd_update
    filter_downloads(item.downloads, item_json_data['downloads'], lang_list, os_list)
  File "gogrepo.py", line 411, in filter_downloads
    fetch_file_info(d, True)
  File "gogrepo.py", line 368, in fetch_file_info
    shelf_etree = xml.etree.ElementTree.fromstring(gzip.decompress(page.read()))
  File "/usr/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 1 more expected)
```

```
15:21:30 | (212 / 285) fetching game details for star_wars_jedi_knight_jedi_academy...
15:21:56 | error
Traceback (most recent call last):
  File "gogrepo.py", line 722, in cmd_update
    filter_downloads(item.downloads, item_json_data['downloads'], lang_list, os_list)
  File "gogrepo.py", line 411, in filter_downloads
    fetch_file_info(d, True)
  File "gogrepo.py", line 368, in fetch_file_info
    shelf_etree = xml.etree.ElementTree.fromstring(gzip.decompress(page.read()))
  File "/usr/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 4577 more expected)
```

```
15:26:31 | (236 / 285) fetching game details for the_darkside_detective_a_fumble_in_the_dark...
15:26:44 | error
Traceback (most recent call last):
  File "gogrepo.py", line 722, in cmd_update
    filter_downloads(item.downloads, item_json_data['downloads'], lang_list, os_list)
  File "gogrepo.py", line 411, in filter_downloads
    fetch_file_info(d, True)
  File "gogrepo.py", line 368, in fetch_file_info
    shelf_etree = xml.etree.ElementTree.fromstring(gzip.decompress(page.read()))
  File "/usr/lib/python3.8/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 1 more expected)
```

**Comment by sairuk** [comment]
i didn't see a notification for this for whatever reason, is this still an issue you are facing? 

We can probably just handle this error better, and perhaps retry

**Comment by sairuk** [comment]
i've merged in pr https://github.com/sairuk/gogrepo/pull/2/ now which added some IncompleteRead support, might help with this

**Comment by ghost** [comment]
Hey, thanks for the update. I pulled the newest version and it successfully got the hashes and was able to download those games. Sometimes, things seem to fail for no reason, but like the linked issue mentions, it seems that their CDN is really flaky.

**Comment by sairuk** [comment]
yeh ok i'll close this for now then, see how we go
